name: Deploy
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/proyectos/mi-laravel || git clone https://github.com/Misael-Git/laravel-misael.git ~/proyectos/mi-laravel
            cd ~/proyectos/mi-laravel
            git pull origin main
            docker compose up -d --build